insert into allergens
values (1, 'A', 'Grains containing gluten'),
       (2, 'B', 'Crustaceans'),
       (3, 'C', 'Egg'),
       (4, 'D', 'Fish'),
       (5, 'E', 'Peanuts'),
       (6, 'F', 'Soy'),
       (7, 'G', 'Milk or lactose'),
       (8, 'H', 'Edible nuts'),
       (9, 'L', 'Celery'),
       (10, 'M', 'Mustard'),
       (11, 'N', 'Sesame'),
       (12, 'O', 'Sulphites'),
       (13, 'P', 'Lupines'),
       (14, 'R', 'Molluscs');