insert into categories
values (1, 'Cabbage'),
       (2, 'Mushrooms'),
       (3, 'Broccoli'),
       (4, 'Tofu'),
       (5, 'Soy Nuts'),
       (6, 'Soy Yogurt'),
       (7, 'Soy Milk'),
       (8, 'Soy Sauce'),
       (9, 'Nuts'),
       (10, 'Pork'),
       (11, 'Fish'),
       (12, 'Seafood'),
       (13, 'Beef'),
       (14, 'Veal'),
       (15, 'Licorice'),
       (16, 'Raisin'),
       (17, 'Tomatoes');